In [55]:
import pandas as pd 
data = pd.read_csv('202101-202106(1).csv',encoding='utf-8')
data['上线月份'] = pd.to_datetime(data['上线月份'], format='%Y%m').dt.strftime('%Y-%m')
data.head()

,零件号,仓库,相似ID,新旧,上线月份,1,2,3,4,5,6
0,56D601025C 8Z8,3001,D60102-3001,old,2016-04,31,22.0,20.0,22.0,27.0,13.0
1,5GD853671E 9B9,8012,D85367-8012,old,2018-11,1,2.0,1.0,6.0,6.0,5.0
2,18D839698F,8015,D83969-8015,old,2016-04,5,7.0,4.0,5.0,9.0,8.0
3,ZVI000001 ROT,1000-3,I00000-1000-3,new,2021-02,46,38.0,163.0,123.0,90.0,49.0
4,3CC821112,3001,C82111-3001,new,2021-01,5,3.0,2.0,NaN,2.0,14.0

In [56]:
real_demods_info = data[data['新旧']=='new']
real_demods_info = real_demods_info.fillna(1)
real_demods_info

,零件号,仓库,相似ID,新旧,上线月份,1,2,3,4,5,6
3,ZVI000001 ROT,1000-3,I00000-1000-3,new,2021-02,46,38.0,163.0,123.0,90.0,49.0
4,3CC821112,3001,C82111-3001,new,2021-01,5,3.0,2.0,1.0,2.0,14.0
5,LVM765035Z2,5003,M76503-5003,new,2021-06,6,1.0,1.0,1.0,1.0,1.0
16,PHN02011101,8023,N02011-8023,new,2021-03,1200,492.0,256.0,837.0,103.0,400.0
26,11D821022,8022,D82102-8022,new,2021-03,13,1.0,9.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
52674,3GB853689C SGU,8015,B85368-8015,new,2021-03,1,1.0,1.0,1.0,1.0,1.0
52676,3ED807724B,8013,D80772-8013,new,2021-03,1,1.0,1.0,1.0,1.0,1.0
52681,18A721039,1000-1,A72103-1000-1,new,2021-04,1,1.0,1.0,2.0,1.0,1.0
52691,ZCX01911303,5002,X01911-5002,new,2021-04,6,1.0,1.0,1.0,1.0,1.0
52693,5NG868994F 82V,8023,G86899-8023,new,2021-03,1,1.0,1.0,1.0,1.0,1.0

In [57]:
pred_svg_info = pd.read_csv('svg预测(2).csv',encoding='utf-8')
for i in ['1','2','3','4','5','6']:
    pred_svg_info[i] = [1 if x <0.01 else x for x in pred_svg_info[i]]
pred_svg_info = pred_svg_info.fillna(1)

In [58]:
pred_svg_info

,零件号,仓库,上线月份,1,2,3,4,5,6
0,11D807185B D7X,8012,202105,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,5NH807221 GRU,8012,202101,1.000000,0.333333,0.666667,0.400000,0.266667,0.190476
2,3CG858819,1000-1,202104,1.000000,0.333333,0.166667,0.100000,0.066667,0.047619
3,5NG831055K,1000-1,202104,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
4,34D853651H RYP,3002,202105,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...
7042,330971072BP,1000-1,202106,1.000000,1.000000,1.000000,0.100000,0.066667,0.047619
7043,3CG807050B,8011,202106,1.000000,1.000000,2.000000,1.333333,0.666667,0.800000
7044,04E905612C,5002,202101,2054.576667,2212.250000,2054.683333,2124.900000,2157.500000,1739.800761
7045,11D853688E 2ZZ,1000-1,202105,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
7046,32D853841A 2ZZ,8023,202101,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [59]:
output = pd.merge(real_demods_info,pred_svg_info,on =['零件号','仓库'],how ='left')
output.head(10)

,零件号,仓库,相似ID,新旧,上线月份_x,1_x,2_x,3_x,4_x,5_x,6_x,上线月份_y,1_y,2_y,3_y,4_y,5_y,6_y
0,ZVI000001 ROT,1000-3,I00000-1000-3,new,2021-02,46,38.0,163.0,123.0,90.0,49.0,202102,46.000000,40.666667,101.833333,110.300000,103.533333,87.952381
1,3CC821112,3001,C82111-3001,new,2021-01,5,3.0,2.0,1.0,2.0,14.0,202101,2.362448,3.213043,2.391967,1.816993,1.000000,1.000000
2,LVM765035Z2,5003,M76503-5003,new,2021-06,6,1.0,1.0,1.0,1.0,1.0,202106,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
3,PHN02011101,8023,N02011-8023,new,2021-03,1200,492.0,256.0,837.0,103.0,400.0,202103,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
4,11D821022,8022,D82102-8022,new,2021-03,13,1.0,9.0,1.0,1.0,1.0,202103,1.000000,1.000000,1.000000,0.333333,0.166667,0.100000
5,6RD612041AG,1000-2,D61204-1000-2,new,2021-01,2,3.0,3.0,8.0,11.0,7.0,202101,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
6,5NG839432F 5AP,8023,G83943-8023,new,2021-04,2,1.0,1.0,5.0,2.0,4.0,202104,1.000000,2.666667,3.833333,4.700000,4.266667,6.142857
7,3ED807217B GRU,8015,D80721-8015,new,2021-06,2,1.0,3.0,1.0,1.0,3.0,202106,2.000000,1.333333,2.166667,1.300000,1.200000,1.714286
8,1EA959895,1000-3,A95989-1000-3,new,2021-06,4,1.0,2.0,2.0,5.0,6.0,202106,4.000000,1.333333,1.666667,1.800000,2.866667,3.761905
9,5NH854732A GRU,5001,H85473-5001,new,2021-02,2,24.0,62.0,3.0,2.0,4.0,202102,3.000000,18.333333,39.333333,24.800000,17.200000,13.428571

In [60]:
output['2_mape'] = abs(output['1_y']-output['2_x'])/output['2_x']
output['3_mape'] = abs(output['2_y']-output['3_x'])/output['3_x']
output['4_mape'] = abs(output['3_y']-output['4_x'])/output['4_x']
output['5_mape'] = abs(output['4_y']-output['5_x'])/output['5_x']
output['6_mape'] = abs(output['5_y']-output['6_x'])/output['6_x']
output.head()

,零件号,仓库,相似ID,新旧,上线月份_x,1_x,2_x,3_x,4_x,5_x,...,2_y,3_y,4_y,5_y,6_y,2_mape,3_mape,4_mape,5_mape,6_mape
0,ZVI000001 ROT,1000-3,I00000-1000-3,new,2021-02,46,38.0,163.0,123.0,90.0,...,40.666667,101.833333,110.300000,103.533333,87.952381,0.210526,0.750511,0.172087,0.225556,1.112925
1,3CC821112,3001,C82111-3001,new,2021-01,5,3.0,2.0,1.0,2.0,...,3.213043,2.391967,1.816993,1.000000,1.000000,0.212517,0.606521,1.391967,0.091503,0.928571
2,LVM765035Z2,5003,M76503-5003,new,2021-06,6,1.0,1.0,1.0,1.0,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,PHN02011101,8023,N02011-8023,new,2021-03,1200,492.0,256.0,837.0,103.0,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.997967,0.996094,0.998805,0.990291,0.997500
4,11D821022,8022,D82102-8022,new,2021-03,13,1.0,9.0,1.0,1.0,...,1.000000,1.000000,0.333333,0.166667,0.100000,0.000000,0.888889,0.000000,0.666667,0.833333

In [61]:
mape_info  = output[['零件号','仓库','2_mape','3_mape','4_mape','5_mape','6_mape']]
mape_info.mean()

/var/folders/tq/ty6dg6810571sz60cwyxn8ch0000gn/T/ipykernel_39928/946967771.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  mape_info.mean()

2_mape    1.947767
3_mape    1.522261
4_mape    1.013639
5_mape    1.004487
6_mape    1.022994
dtype: float64

In [63]:
# 计算mape，wmape 占比情况

# 定义区间
import matplotlib.pyplot as plt
import seaborn as sns

bins = [0, 0.10, 0.30, 0.50, 1.00, 100000]
test = mape_info.copy()
# 使用cut函数将数据分成不同区间
for i in ['2_mape','3_mape','4_mape','5_mape','6_mape']:
    print(test[i].mean())
    test[i] = pd.cut(test[i], bins=bins, labels=['0-10%', '10%-30%', '30%-50%', '50%-100%', '>100%'],right =False)
    test[i].replace('NaN','0',inplace =True)
# 计算每个区间中的数据数量
    print('新品第',i.split('_')[0],'月误差')
    print(test[i].value_counts(normalize=True))

1.9477670984528932
新品第 2 月误差
0-10%       0.631474
50%-100%    0.175110
>100%       0.139066
30%-50%     0.029800
10%-30%     0.024549
Name: 2_mape, dtype: float64
1.522261483013391
新品第 3 月误差
0-10%       0.407833
50%-100%    0.382148
>100%       0.090535
30%-50%     0.079041
10%-30%     0.040443
Name: 3_mape, dtype: float64
1.0136394175840944
新品第 4 月误差
0-10%       0.382716
50%-100%    0.373634
30%-50%     0.087555
10%-30%     0.083865
>100%       0.072229
Name: 4_mape, dtype: float64
1.0044869288002092
新品第 5 月误差
0-10%       0.395487
50%-100%    0.369377
30%-50%     0.090961
>100%       0.076061
10%-30%     0.068114
Name: 5_mape, dtype: float64
1.022994151280441
新品第 6 月误差
0-10%       0.372499
50%-100%    0.357457
30%-50%     0.098056
>100%       0.088406
10%-30%     0.083582
Name: 6_mape, dtype: float64