In [1]:
import cx_Oracle
cx_Oracle.init_oracle_client(lib_dir=r"/Users/kaka/Downloads/instantclient_18_1")
from sqlalchemy import create_engine
import json
import pandas as pd
import os
import sqlalchemy

In [5]:
def mysql_info():
    """数据上传"""
    username = 'nppbuf'
    password = 'Svwnppbuf321'
    hostname = '10.122.6.59'
    port = 1521
    service_name = 'b2bt'
    dsn = cx_Oracle.makedsn(hostname, port, service_name=service_name)
    # 连接 Oracle 数据库
    connection = cx_Oracle.connect(user=username, password=password, dsn=dsn)
    return connection

In [9]:
data = pd.read_csv('111.csv',encoding ='utf-8').drop('Unnamed: 0',axis =1)
conn  = mysql_info()
# 定义游标
cursor = conn.cursor()
# 执行插入操作
sql = "INSERT INTO nppbuf.T_DD_FORECAST_DETAIL_test (hostpartid, hostlocid, dshostid, year, month, pred_values) VALUES (:1, :2, :3, :4, :5, :6)"
for index, row in data.iterrows():
    try:
        cursor.execute(sql, (row['hostpartid'], row['hostlocid'], row['dshostid'], row['year'], row['month'], row['pred_values']))
    except:
        print(index)
# 提交事务
conn.commit()

# 关闭游标和连接
cursor.close()
conn.close()

12135
14573
14580

In [14]:
def get_full_skulist(connection):
    sql_query = """  select 
                  *
          from nppbuf.T_DD_FORECAST_DETAIL_FJHIS  where HOSTPARTID ='N  91174301'
    """
    # 执行 SQL 查询，并按批次抽取数据
    query_chunks = pd.read_sql(sql_query, connection)
    # 遍历查询结果的每个批次，并将其合并为一个 DataFrame
    return query_chunks

connection  = mysql_info()

new_df = get_full_skulist(connection)

/Users/kaka/opt/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [15]:
# new_df[new_df['HOSTLOCID']=='5002'].groupby([''])
new_df['HISTORYBEGDATE'] = pd.to_datetime(new_df['HISTORYBEGDATE'], format='%Y%m%d').dt.strftime('%Y-%m-%d')
new_df["year"] = pd.to_datetime(new_df['HISTORYBEGDATE']).dt.year.astype(int)
new_df["month"] = pd.to_datetime(new_df['HISTORYBEGDATE']).dt.month.astype(int)

test = new_df[new_df['HOSTLOCID']=='5002']
test.groupby(['HOSTPARTID','DSHOSTID','year','month'])['HISTORYAMOUNT'].sum().reset_index()

     HOSTPARTID DSHOSTID  year  month  HISTORYAMOUNT
0   N  91174301   DEALER  2019      3             18
1   N  91174301   DEALER  2019      4             66
2   N  91174301   DEALER  2019      5             78
3   N  91174301   DEALER  2019      6             57
4   N  91174301   DEALER  2019      7             25
5   N  91174301   DEALER  2019      8             62
6   N  91174301   DEALER  2019      9             66
7   N  91174301   DEALER  2019     10             96
8   N  91174301   DEALER  2019     11             60
9   N  91174301   DEALER  2019     12             52
10  N  91174301   DEALER  2020      1             24
11  N  91174301   DEALER  2020      2             30
12  N  91174301   DEALER  2020      3             88
13  N  91174301   DEALER  2020      4             36
14  N  91174301   DEALER  2020      5             30
15  N  91174301   DEALER  2020      6             86
16  N  91174301   DEALER  2020      7             72
17  N  91174301   DEALER  2020      8             72
18  N  91174301   DEALER  2020      9             82
19  N  91174301   DEALER  2020     10             72
20  N  91174301   DEALER  2020     11             30
21  N  91174301   DEALER  2020     12             46
22  N  91174301   DEALER  2021      1             46
23  N  91174301   DEALER  2021      2             12
24  N  91174301   DEALER  2021      3             28
25  N  91174301   DEALER  2021      4             30
26  N  91174301   DEALER  2021      5             37
27  N  91174301   DEALER  2021      6             50
28  N  91174301   DEALER  2021      7             29
29  N  91174301   DEALER  2023      3             18
30  N  91174301   DEALER  2023      4             66
31  N  91174301   DEALER  2023      5             78
32  N  91174301   DEALER  2023      6             57
33  N  91174301   DEALER  2023      7             25
34  N  91174301   DEALER  2023      8             62